//! The showcase page, checked against the data it actually gets.
//!
//! A front end is the easiest thing in a repository to let rot: nothing
//! compiles it, and a renamed field in the exporter turns a panel blank rather
//! than failing anything. So the page declares the fields it reads in one
//! `CONTRACT` object, and these tests assert that object against a bundle
//! generated by the real command.

mod common;

use common::Archive;
use std::collections::BTreeSet;
use std::path::Path;

fn page() -> String {
    std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("ui/index.html")).unwrap()
}

/// The `CONTRACT` object's field lists, by group.
///
/// Parsed out of the page rather than restated here — a copy in this file
/// would be the second list that drifts, which is the failure being guarded
/// against in the first place.
fn contract() -> Vec<(String, Vec<String>)> {
    let text = page();
    let start = text
        .find("const CONTRACT = {")
        .expect("the page declares its contract");
    let body = &text[start..];
    let end = body.find("\n};").expect("CONTRACT is closed");
    let mut out = Vec::new();
    for line in body[..end].lines() {
        let line = line.trim();
        let Some((key, rest)) = line.split_once(": [") else {
            continue;
        };
        let fields: Vec<String> = rest
            .trim_end_matches("],")
            .split(',')
            .map(|f| f.trim().trim_matches('\'').to_string())
            .filter(|f| !f.is_empty())
            .collect();
        if !fields.is_empty() {
            out.push((key.to_string(), fields));
        }
    }
    assert!(out.len() >= 5, "parsed too little of CONTRACT: {out:?}");
    out
}

/// An archive with a bit of everything the page renders.
fn archive() -> Archive {
    let a = Archive::new();
    let src = a.path("mine.md");
    std::fs::write(&src, "What I think.\n").unwrap();
    a.run(&[
        "ingest",
        &src.display().to_string(),
        "-d",
        "philosophy",
        "-o",
        "authored",
        "--as",
        "mine.md",
    ]);
    a.write(
        "persona/held.md",
        "---\nid: held\nkind: belief\nclaim: Argues from cases.\nconfidence: high\n\
         status: affirmed\nevidence:\n  - raw/philosophy/mine.md\n---\n\nBecause.\n",
    );
    for (slug, other) in [("alpha", "beta"), ("beta", "alpha")] {
        a.write(
            &format!("wiki/philosophy/{slug}.md"),
            &format!(
                "---\ntitle: {slug}\ndomain: philosophy\norigin: authored\ntags: [t]\n\
                 status: stable\nsources: [raw/philosophy/mine.md]\n---\n\nSee [[{other}]].\n"
            ),
        );
    }
    a.write(
        "wiki/philosophy/machine.md",
        "---\ntitle: Machine\ndomain: philosophy\norigin: extrapolated\ntags: [t]\n\
         status: stable\npersona:\n  - held\n---\n\nSee [[alpha]].\n",
    );
    a.run(&["index"]);
    let mut cmd = a.cmd(&["review", "machine", "--approve"]);
    cmd.env("SENTINEL_REVIEWER", "khaneight");
    assert!(cmd.output().unwrap().status.success());
    a.run(&["index"]);
    a
}

fn export_ui(a: &Archive) -> (tempfile::TempDir, serde_json::Value) {
    let dir = tempfile::tempdir().unwrap();
    let site = dir.path().join("site");
    let ui = dir.path().join("ui");
    let out = a.output(&[
        "export",
        "--out",
        &site.display().to_string(),
        "--flat",
        "--ui",
        &ui.display().to_string(),
        "--json",
    ]);
    assert_eq!(out.status.code(), Some(0), "{}", common::stderr(&out));
    let bundle: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(ui.join("bundle.json")).unwrap()).unwrap();
    (dir, bundle)
}

#[test]
fn every_field_the_page_reads_exists_in_a_real_bundle() {
    // The point of the whole file. A renamed key in `export` fails here rather
    // than blanking a panel on a deployed site.
    let a = archive();
    let (_dir, bundle) = export_ui(&a);

    for (group, fields) in contract() {
        let sample = match group.as_str() {
            "top" => bundle.clone(),
            "in_progress" => bundle["in_progress"].clone(),
            "layer" => bundle["layers"][0].clone(),
            "edge_kind" => bundle["edge_kinds"][0].clone(),
            "node" => bundle["nodes"][0].clone(),
            "edge" => bundle["edges"][0].clone(),
            "trait" => bundle["persona"][0].clone(),
            "progress" => bundle["progress"][0].clone(),
            other => panic!("CONTRACT has a group `{other}` this test does not check"),
        };
        assert!(
            !sample.is_null(),
            "the fixture produced no `{group}` to check against — this test \
             would pass while verifying nothing"
        );
        let present: BTreeSet<&str> = sample
            .as_object()
            .unwrap_or_else(|| panic!("`{group}` is not an object: {sample}"))
            .keys()
            .map(String::as_str)
            .collect();
        for field in fields {
            assert!(
                present.contains(field.as_str()),
                "the page reads `{group}.{field}`, which the bundle does not \
                 publish. Fields present: {present:?}"
            );
        }
    }
}

#[test]
fn the_page_is_self_contained() {
    // It has to work on any static host, offline, behind whatever content
    // policy the user's site sets. One `fetch` of its own data file, nothing
    // else — a CDN reference would make it stop working the day that CDN does.
    let text = page();
    for pattern in [
        "http://",
        "https://",
        "//cdn",
        "<script src",
        "<link rel=\"stylesheet\"",
    ] {
        assert!(
            !text.contains(pattern),
            "the page references something external (`{pattern}`), so it will \
             not work offline or under a strict content policy"
        );
    }
    assert_eq!(
        text.matches("fetch(").count(),
        1,
        "exactly one network read: its own bundle"
    );
    assert!(text.contains("fetch('bundle.json')"));
}

#[test]
fn export_ui_writes_a_page_and_the_data_it_needs() {
    // A flag that wrote the page without its bundle would produce a site whose
    // only content is an error message.
    let a = archive();
    let dir = tempfile::tempdir().unwrap();
    let ui = dir.path().join("showcase");
    let v = a.json(&[
        "export",
        "--out",
        &dir.path().join("site").display().to_string(),
        "--flat",
        "--ui",
        &ui.display().to_string(),
    ]);
    assert_eq!(v["ui"], ui.display().to_string());
    assert!(ui.join("index.html").exists());
    assert!(ui.join("bundle.json").exists());

    // Byte-identical to the file in the tree, so what ships is what is reviewed.
    assert_eq!(
        std::fs::read_to_string(ui.join("index.html")).unwrap(),
        page()
    );
}

#[test]
fn the_page_marks_work_the_clone_wrote() {
    // The UI-level form of the rule the exporter enforces: an article the
    // machine wrote is never presented as though its author wrote it.
    let a = archive();
    let (_dir, bundle) = export_ui(&a);
    let machine = bundle["nodes"]
        .as_array()
        .unwrap()
        .iter()
        .find(|n| n["slug"] == "machine")
        .expect("the approved extrapolated article is published");
    assert_eq!(machine["extrapolated"], true);

    let text = page();
    assert!(
        text.contains("extrapolated"),
        "the page must branch on it, or the distinction is only in the data"
    );
    assert!(
        text.contains("Written by the clone"),
        "and say so in words, not only in a colour"
    );
}

#[test]
fn a_dry_run_writes_no_page() {
    let a = archive();
    let dir = tempfile::tempdir().unwrap();
    let ui = dir.path().join("showcase");
    a.run(&[
        "export",
        "--out",
        &dir.path().join("site").display().to_string(),
        "--flat",
        "--ui",
        &ui.display().to_string(),
        "--dry-run",
    ]);
    assert!(!ui.exists(), "--dry-run must write nothing at all");
}

#[test]
fn the_bundle_the_ui_gets_respects_the_approval_gate() {
    // The showcase reads the same published set as the site. If it did not, an
    // unapproved article could appear in the graph of work that was published.
    let a = archive();
    a.write(
        "wiki/philosophy/unsigned.md",
        "---\ntitle: Unsigned\ndomain: philosophy\norigin: extrapolated\ntags: [t]\n\
         status: stable\npersona:\n  - held\n---\n\nNot approved.\n",
    );
    a.run(&["index"]);
    let (_dir, bundle) = export_ui(&a);
    let slugs: Vec<&str> = bundle["nodes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|n| n["slug"].as_str().unwrap())
        .collect();
    assert!(!slugs.contains(&"unsigned"), "{slugs:?}");
    assert_eq!(bundle["in_progress"]["awaiting_approval"], 1);
}
