use std::collections::HashSet;
use std::io;

use colored::Colorize;
use walkdir::WalkDir;

use crate::core::frontmatter;
use crate::core::links::{self, LinkGraph};
use crate::core::paths;

pub fn run() -> io::Result<()> {
    let wiki_dir = paths::wiki_dir();
    if !wiki_dir.exists() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            "Wiki directory not found. Run `sentinel init` first.",
        ));
    }

    let mut articles = Vec::new();

    // Scan all wiki markdown files
    for entry in WalkDir::new(&wiki_dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file() && e.path().extension().is_some_and(|ext| ext == "md"))
    {
        let path = entry.path();
        let rel_path = paths::rel(path);

        if let Ok(article) = frontmatter::parse_file(path, &rel_path) {
            articles.push(article);
        }
    }

    // Build link graph
    let mut graph = LinkGraph::default();
    let graph_entries: Vec<(String, Vec<String>)> = articles
        .iter()
        .map(|a| {
            let slug = slug_from_path(&a.rel_path);
            let full_content = std::fs::read_to_string(paths::archive_root().join(&a.rel_path))
                .unwrap_or_default();
            let linked = links::extract_wikilinks(&full_content);
            (slug, linked)
        })
        .collect();

    let all_slugs: HashSet<String> = graph_entries.iter().map(|(s, _)| s.clone()).collect();
    graph.rebuild(graph_entries);
    let orphans = graph.orphans(&all_slugs);
    graph.save()?;

    // Sort articles for index generation
    let mut sorted = articles.clone();
    sorted.sort_by(|a, b| {
        let title_a = a.frontmatter.title.as_deref().unwrap_or(&a.rel_path);
        let title_b = b.frontmatter.title.as_deref().unwrap_or(&b.rel_path);
        title_a.to_lowercase().cmp(&title_b.to_lowercase())
    });

    // Generate _master.md
    let mut master =
        String::from("# Master Index\n\n*Auto-generated by sentinel. Do not edit manually.*\n\n");
    for article in &sorted {
        let title = article
            .frontmatter
            .title
            .as_deref()
            .unwrap_or(&article.rel_path);
        let slug = slug_from_path(&article.rel_path);
        let origin = article.frontmatter.origin.as_deref().unwrap_or("unknown");
        let status = article.frontmatter.status.as_deref().unwrap_or("draft");
        master.push_str(&format!("- [[{slug}|{title}]] `{origin}` `{status}`\n"));
    }
    std::fs::write(paths::index_dir().join("_master.md"), master)?;

    // Generate _by-domain.md
    let mut by_domain: std::collections::BTreeMap<String, Vec<&frontmatter::WikiArticle>> =
        std::collections::BTreeMap::new();
    for article in &sorted {
        let domain = article
            .frontmatter
            .domain
            .clone()
            .unwrap_or_else(|| "uncategorized".to_string());
        by_domain.entry(domain).or_default().push(article);
    }

    let mut domain_index = String::from(
        "# Index by Domain\n\n*Auto-generated by sentinel. Do not edit manually.*\n\n",
    );
    for (domain, domain_articles) in &by_domain {
        domain_index.push_str(&format!("## {domain}\n\n"));
        for article in domain_articles {
            let title = article
                .frontmatter
                .title
                .as_deref()
                .unwrap_or(&article.rel_path);
            let slug = slug_from_path(&article.rel_path);
            domain_index.push_str(&format!("- [[{slug}|{title}]]\n"));
        }
        domain_index.push('\n');
    }
    std::fs::write(paths::index_dir().join("_by-domain.md"), domain_index)?;

    // Generate _recent.md (sorted by updated date, descending)
    let mut by_date = articles.clone();
    by_date.sort_by(|a, b| {
        let date_a = a.frontmatter.updated.as_deref().unwrap_or("0000-00-00");
        let date_b = b.frontmatter.updated.as_deref().unwrap_or("0000-00-00");
        date_b.cmp(date_a)
    });

    let mut recent = String::from(
        "# Recently Modified\n\n*Auto-generated by sentinel. Do not edit manually.*\n\n",
    );
    for article in by_date.iter().take(50) {
        let title = article
            .frontmatter
            .title
            .as_deref()
            .unwrap_or(&article.rel_path);
        let slug = slug_from_path(&article.rel_path);
        let updated = article.frontmatter.updated.as_deref().unwrap_or("unknown");
        recent.push_str(&format!("- [[{slug}|{title}]] — {updated}\n"));
    }
    std::fs::write(paths::index_dir().join("_recent.md"), recent)?;

    // Generate _orphans.md
    let mut orphans_md = String::from(
        "# Orphan Pages\n\n*Pages with no incoming backlinks. Auto-generated by sentinel.*\n\n",
    );
    if orphans.is_empty() {
        orphans_md.push_str("No orphan pages found.\n");
    } else {
        for slug in &orphans {
            orphans_md.push_str(&format!("- [[{slug}]]\n"));
        }
    }
    std::fs::write(paths::index_dir().join("_orphans.md"), orphans_md)?;

    crate::core::log::append("index", &format!("{} articles indexed", sorted.len()))?;

    println!("{}", "Index rebuilt.".green());
    println!("  Articles indexed: {}", sorted.len());
    println!("  Domains:          {}", by_domain.len());
    println!("  Orphan pages:     {}", orphans.len());

    Ok(())
}

/// Extract a slug from a wiki article path like "wiki/philosophy/stoicism.md" → "stoicism"
fn slug_from_path(rel_path: &str) -> String {
    std::path::Path::new(rel_path)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or(rel_path)
        .to_string()
}
