use std::collections::{BTreeMap, HashSet};
use std::io;

use colored::Colorize;

use serde::Serialize;

use crate::core::atomic;
use crate::core::compilation::Compilation;
use crate::core::links::{self, LinkGraph};
use crate::core::manifest::Manifest;
use crate::core::output;
use crate::core::paths;
use crate::core::slug;
use crate::core::wiki::{self, LoadedArticle};

/// Rebuild every piece of derived state: the link graph, the four generated
/// indexes, and the raw → wiki compilation mapping in the manifest.
pub fn run() -> io::Result<()> {
    // A complete view is a precondition, not a nicety: everything below
    // overwrites durable state derived from `articles`, so a file skipped for
    // being unreadable would be silently deleted from the indexes and from the
    // manifest's compilation mapping.
    let articles = wiki::load_all()?.require_complete()?;

    // Build link graph
    let mut graph = LinkGraph::default();
    let graph_entries: Vec<(String, Vec<String>)> = articles
        .iter()
        // Both ends canonical, so an edge written `[[Compile Loop]]` lands on
        // the same node as one written `[[compile-loop]]`.
        .map(|a| {
            let targets = links::extract_wikilinks(&a.content)
                .iter()
                .map(|t| slug::canonical(t))
                .filter(|t| !t.is_empty())
                .collect();
            (a.canonical_slug(), targets)
        })
        .collect();

    let all_slugs: HashSet<String> = graph_entries.iter().map(|(s, _)| s.clone()).collect();
    graph.rebuild(graph_entries);
    let orphans = graph.orphans(&all_slugs);
    graph.save()?;

    // Reconcile the manifest's raw → wiki mapping from what the articles cite.
    let mut manifest = Manifest::load()?;
    let compilation = Compilation::derive(&articles, &manifest);
    let remapped = compilation.apply_to(&mut manifest);
    manifest.save()?;
    let uncompiled = compilation.uncompiled(&manifest).len();

    // Sort articles for index generation
    let mut sorted: Vec<&LoadedArticle> = articles.iter().collect();
    // Title, then path: two articles with the same title would otherwise order
    // by whatever the filesystem walk returned, and these files live in a git repo.
    sorted.sort_by_key(|a| (a.title().to_lowercase(), a.rel_path().to_string()));

    // Generate _master.md
    let mut master = header("Master Index", None::<String>);
    for article in &sorted {
        let origin = article
            .article
            .frontmatter
            .origin
            .as_deref()
            .unwrap_or("unknown");
        let status = article
            .article
            .frontmatter
            .status
            .as_deref()
            .unwrap_or("draft");
        master.push_str(&format!(
            "- [[{}|{}]] `{origin}` `{status}`\n",
            article.slug(),
            article.title()
        ));
    }
    let mut wrote = atomic::write_if_changed(&paths::index_dir().join("_master.md"), master)?;

    // Generate _by-domain.md
    let mut by_domain: BTreeMap<&str, Vec<&LoadedArticle>> = BTreeMap::new();
    for article in &sorted {
        let domain = article
            .article
            .frontmatter
            .domain
            .as_deref()
            .unwrap_or("uncategorized");
        by_domain.entry(domain).or_default().push(article);
    }

    let mut domain_index = header("Index by Domain", None::<String>);
    for (domain, domain_articles) in &by_domain {
        domain_index.push_str(&format!("## {domain}\n\n"));
        for article in domain_articles {
            domain_index.push_str(&format!("- [[{}|{}]]\n", article.slug(), article.title()));
        }
        domain_index.push('\n');
    }
    wrote |= atomic::write_if_changed(&paths::index_dir().join("_by-domain.md"), domain_index)?;

    // Generate _recent.md (sorted by updated date, descending)
    let mut by_date: Vec<&LoadedArticle> = articles.iter().collect();
    by_date.sort_by(|a, b| {
        let date_a = a
            .article
            .frontmatter
            .updated
            .as_deref()
            .unwrap_or("0000-00-00");
        let date_b = b
            .article
            .frontmatter
            .updated
            .as_deref()
            .unwrap_or("0000-00-00");
        date_b
            .cmp(date_a)
            .then_with(|| a.rel_path().cmp(b.rel_path()))
    });

    // A generated file that silently shows a subset reads as the whole list.
    const RECENT_LIMIT: usize = 50;
    let mut recent = header(
        "Recently Modified",
        (by_date.len() > RECENT_LIMIT).then(|| {
            format!(
                "The {RECENT_LIMIT} most recently updated of {} articles. \
                 Auto-generated by sentinel. Do not edit manually.",
                by_date.len()
            )
        }),
    );
    for article in by_date.iter().take(RECENT_LIMIT) {
        let updated = article
            .article
            .frontmatter
            .updated
            .as_deref()
            .unwrap_or("unknown");
        recent.push_str(&format!(
            "- [[{}|{}]] — {updated}\n",
            article.slug(),
            article.title()
        ));
    }
    wrote |= atomic::write_if_changed(&paths::index_dir().join("_recent.md"), recent)?;

    // Generate _orphans.md
    let mut sorted_orphans = orphans.clone();
    sorted_orphans.sort();
    let mut orphans_md = header(
        "Orphan Pages",
        Some("Pages with no incoming backlinks. Auto-generated by sentinel."),
    );
    if sorted_orphans.is_empty() {
        orphans_md.push_str("No orphan pages found.\n");
    } else {
        for slug in &sorted_orphans {
            orphans_md.push_str(&format!("- [[{slug}]]\n"));
        }
    }
    wrote |= atomic::write_if_changed(&paths::index_dir().join("_orphans.md"), orphans_md)?;

    // Generate _uncompiled.md — the work queue an agent reads to decide what
    // to compile next. Derived state belongs in index/ like everything else.
    let mut uncompiled_md = header(
        "Uncompiled Sources",
        Some("Raw documents no wiki article cites in its `sources:`. Auto-generated by sentinel."),
    );
    let pending = compilation.uncompiled(&manifest);
    if pending.is_empty() {
        uncompiled_md.push_str("Every raw document has been compiled.\n");
    } else {
        for entry in &pending {
            uncompiled_md.push_str(&format!(
                "- `{}` — {} ({})\n",
                entry.raw_path, entry.title, entry.origin
            ));
        }
    }
    wrote |= atomic::write_if_changed(&paths::index_dir().join("_uncompiled.md"), uncompiled_md)?;

    // Last, deliberately. The dashboard reports the link graph and the
    // compilation mapping, both of which are rewritten above — generated any
    // earlier it would describe the archive as it was before this very command
    // ran, which is precisely the staleness it warns the reader about.
    //
    // Two things keep it from churning forever. The date carries no time of
    // day, so regenerating twice in one day with nothing changed produces
    // identical bytes and no write at all. And the result deliberately does
    // *not* feed `wrote`: the page reports the activity log, `index` appends to
    // that log whenever it writes, so counting the dashboard as a change would
    // make every run log, which would change the next run's page, forever.
    // A derived view of news is not itself news.
    let generated_at = chrono::Local::now().format("%Y-%m-%d").to_string();
    let dashboard = super::dashboard::render(&generated_at)?;
    atomic::write_if_changed(&paths::index_dir().join("_dashboard.md"), dashboard)?;

    // A measurement of the archive, after every derived thing is current.
    // Appended only when the counts differ from the last one, so the file is a
    // history of the archive rather than of how often `index` ran.
    let findings = crate::core::lint::analyze(&articles, &manifest, &paths::archive_root());
    let snapshot = crate::core::history::Snapshot {
        at: chrono::Local::now().format("%Y-%m-%d %H:%M").to_string(),
        wiki_articles: sorted.len(),
        raw_documents: manifest.count(),
        uncompiled,
        orphans: orphans.len(),
        errors: crate::core::lint::count(&findings, crate::core::lint::Severity::Error),
        warnings: crate::core::lint::count(&findings, crate::core::lint::Severity::Warning),
        wanted: links::wanted(&articles).len(),
        links: graph.forward.values().map(Vec::len).sum(),
    };
    crate::core::history::record(&snapshot)?;

    // Generated output is deterministic, so an index that changed nothing is a
    // no-op — and logging it would be a change where there was none.
    if wrote || remapped > 0 {
        crate::core::log::append("index", &format!("{} articles indexed", sorted.len()))?;
    }

    if output::is_json() {
        #[derive(Serialize)]
        struct Rebuilt {
            articles_indexed: usize,
            domains: usize,
            orphan_pages: usize,
            uncompiled: usize,
            manifest_remaps: usize,
            unresolved_sources: usize,
            /// False when every generated file already held the right contents.
            files_written: bool,
        }
        return output::emit(
            "index",
            Rebuilt {
                articles_indexed: sorted.len(),
                domains: by_domain.len(),
                orphan_pages: orphans.len(),
                uncompiled,
                manifest_remaps: remapped,
                unresolved_sources: compilation.unresolved.len(),
                files_written: wrote,
            },
        );
    }

    println!("{}", "Index rebuilt.".green());
    println!("  Articles indexed: {}", sorted.len());
    println!("  Domains:          {}", by_domain.len());
    println!("  Orphan pages:     {}", orphans.len());
    println!("  Uncompiled raw:   {uncompiled}");
    if remapped > 0 {
        println!("  Manifest remaps:  {remapped}");
    }
    if !compilation.unresolved.is_empty() {
        println!(
            "  {} {} source citation(s) match no raw document — run `sentinel lint`",
            "!".yellow(),
            compilation.unresolved.len()
        );
    }

    Ok(())
}

fn header(title: &str, note: Option<impl Into<String>>) -> String {
    let note = note
        .map(Into::into)
        .unwrap_or_else(|| "Auto-generated by sentinel. Do not edit manually.".to_string());
    format!("# {title}\n\n*{note}*\n\n")
}
