use std::fs;
use std::io;

use serde::Serialize;

use crate::core::output;
use crate::core::paths::{self, Config, ResolvedRoot, RootSource};

#[derive(Serialize)]
struct Initialized {
    archive: String,
    resolved_via: &'static str,
    created: bool,
    set_default: bool,
}

/// The archive's front page.
///
/// Deliberately free of anything the tool will not keep current. The previous
/// version listed three domains with descriptions, written once at `init` and
/// never updated — so an archive that grew a fourth had a front page quietly
/// disagreeing with it, which is the drift #6 removed from the skills. Live
/// facts are pointed at, not restated.
const SUMMARY_MD: &str = r#"# Archive Knowledge Base

A personal knowledge base compiled and maintained by an agent through the
`sentinel` CLI.

## Domains

See `index/_by-domain.md`, regenerated by `sentinel index`, or run
`sentinel schema` for the domains this archive actually has.

## Structure

- `raw/` — source documents (immutable; never edited)
- `wiki/` — compiled articles
- `index/` — auto-generated indexes (do not edit)
- `meta/` — manifest, link graph, activity log
- `templates/` — article templates, generated from the frontmatter contract

## Where to start

- `sentinel next` — the most valuable thing to do now
- `sentinel status` — counts and health
- `sentinel log` — what has been done recently
"#;

/// Conventions written into a new archive for the agent that will maintain it.
///
/// Deliberately short and mostly pointers: the authoritative contract is
/// `sentinel schema --json`, generated from the code. Anything restated here in
/// prose is something that can drift out of date.
const ARCHIVE_CLAUDE_MD: &str = r#"# Archive

A personal knowledge base maintained by an agent through the `sentinel` CLI.
You write the wiki; the human curates sources and asks questions.

## Orient yourself

```
sentinel next --json      # the single most valuable thing to do now
sentinel status --json    # counts: raw docs, articles, uncompiled, orphans
sentinel schema --json    # frontmatter contract, domains, lint rules
```

Run `sentinel next` first. It reads the whole archive and recommends one
action, with a ready-to-run command and a backlog count for every other
category.

**Do not read `index/_master.md` to orient yourself.** It grows with the
archive and will consume your context before you have done any work. Use
`sentinel search --json` to find specific articles and `sentinel next --json`
to decide what to do.

## Layout

- `raw/` — source documents. **Immutable.** Read them; never edit them.
- `wiki/` — your articles. You own this directory entirely.
- `index/` — generated by `sentinel index`. Never edit; edits are overwritten.
- `meta/` — machine state. Never edit by hand.
- `templates/` — article templates.

## Writing an article

Run `sentinel schema` for the full frontmatter contract. The essentials:

- `title`, `domain`, `origin` are required. `origin` is one of
  `authored` (from the human's own writing), `researched` (you gathered it),
  or `hybrid`.
- **`sources:` is what closes the loop.** List the archive-relative paths of
  the raw documents the article was compiled from. A raw document counts as
  compiled once some article cites it; an article with no `sources:` leaves
  its source stranded in the queue forever.
- Link related concepts with `[[wikilinks]]`, **including ones not written
  yet**. An unresolved link is not a mistake here — it is how the archive
  records what it wants next, and `sentinel next` ranks those gaps by how
  many articles ask for each.

## After writing

```
sentinel index            # rebuild indexes, link graph, and the raw->wiki map
sentinel lint             # exits 2 on errors; warnings alone exit 0
sentinel log <op> "<what happened>"
```

## Preserving voice

For `origin: authored` content, distill and organize — do not editorialize.
Preserve the author's thesis, arguments, and intellectual voice. When adding
research to an authored article, put it in its own section and switch the
article to `origin: hybrid` rather than blending the two.
"#;

pub fn run(resolved: &ResolvedRoot, set_default: bool) -> io::Result<()> {
    let root = paths::archive_root();

    // Falling back to the working directory is convenient in an empty folder and
    // reckless in a populated one — refuse to scatter an archive across someone's
    // home directory or source tree just because they forgot the path argument.
    if resolved.source == RootSource::Cwd && !is_safe_to_initialize(&root)? {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            format!(
                "Refusing to initialize an archive in the non-empty directory {}.\n\
                 Pass an explicit path: `sentinel init <PATH>`.",
                root.display()
            ),
        ));
    }

    let mut created = false;

    // Create directory structure
    let dirs = [
        paths::raw_dir(),
        paths::wiki_dir(),
        paths::index_dir(),
        paths::meta_dir(),
        paths::templates_dir(),
    ];

    for dir in &dirs {
        fs::create_dir_all(dir)?;
    }

    // Create domain subdirectories in both raw/ and wiki/
    for domain in paths::DEFAULT_DOMAINS {
        fs::create_dir_all(paths::raw_domain_dir(domain))?;
        fs::create_dir_all(paths::wiki_domain_dir(domain))?;
    }

    // Create empty manifest if it doesn't exist
    let manifest_path = paths::manifest_path();
    if !manifest_path.exists() {
        fs::write(&manifest_path, r#"{"entries":{}}"#)?;
        created = true;
    }

    // Create empty link graph if it doesn't exist
    let link_graph_path = paths::link_graph_path();
    if !link_graph_path.exists() {
        fs::write(&link_graph_path, r#"{"forward":{},"backlinks":{}}"#)?;
        created = true;
    }

    // Create activity log if it doesn't exist
    let log_path = paths::log_path();
    if !log_path.exists() {
        fs::write(
            &log_path,
            "# Activity Log\n\n*Append-only record of sentinel operations. Parseable: `grep \"^## \\[\" meta/log.md`*\n\n",
        )?;
        created = true;
    }

    // Generated from the published contract rather than hand-copied. The
    // template was a fourth transcription of the frontmatter fields, alongside
    // the lint rule, the schema output, and `ingest`'s validation — and three
    // of those four had already drifted apart (#6, #31).
    let wiki_template = paths::templates_dir().join("wiki-article.md");
    if !wiki_template.exists() {
        fs::write(&wiki_template, super::schema::blank_frontmatter())?;
        created = true;
    }

    // Create raw note template
    let raw_template = paths::templates_dir().join("raw-note.md");
    if !raw_template.exists() {
        fs::write(
            &raw_template,
            r#"---
title:
domain:
origin: authored
ingested:
---

"#,
        )?;
        created = true;
    }

    // Create empty index files
    let index_files = [
        (
            "_master.md",
            "# Master Index\n\n*Auto-generated by sentinel. Do not edit manually.*\n",
        ),
        (
            "_by-domain.md",
            "# Index by Domain\n\n*Auto-generated by sentinel. Do not edit manually.*\n",
        ),
        (
            "_recent.md",
            "# Recently Modified\n\n*Auto-generated by sentinel. Do not edit manually.*\n",
        ),
        (
            "_orphans.md",
            "# Orphan Pages\n\n*Pages with no incoming backlinks. Auto-generated by sentinel.*\n",
        ),
        (
            "_uncompiled.md",
            "# Uncompiled Sources\n\n*Raw documents no wiki article cites in its `sources:`. Auto-generated by sentinel.*\n",
        ),
    ];

    for (name, content) in &index_files {
        let path = paths::index_dir().join(name);
        if !path.exists() {
            fs::write(&path, content)?;
            created = true;
        }
    }

    // Create CLAUDE.md — the schema the README describes but init never wrote,
    // so a fresh archive had no conventions for an agent to read at all.
    let claude_md = root.join("CLAUDE.md");
    if !claude_md.exists() {
        fs::write(&claude_md, ARCHIVE_CLAUDE_MD)?;
        created = true;
    }

    // Create SUMMARY.md if it doesn't exist
    let summary_path = root.join("SUMMARY.md");
    if !summary_path.exists() {
        fs::write(&summary_path, SUMMARY_MD)?;
        created = true;
    }

    // Re-running `init` on a complete archive creates nothing, so recording
    // "Archive initialized" would log an event that did not happen — the same
    // reason `lint` stopped logging.
    if created {
        crate::core::log::append("init", "Archive initialized")?;
    }

    if output::is_json() {
        return output::emit(
            "init",
            Initialized {
                archive: root.display().to_string(),
                resolved_via: resolved.source.describe(),
                created,
                set_default,
            },
        );
    }

    println!("Archive initialized at {}", root.display());
    println!("  raw/       — source documents");
    println!("  wiki/      — compiled knowledge");
    println!("  index/     — auto-generated indexes");
    println!("  meta/      — manifest, link graph, activity log");
    println!("  templates/ — article templates");

    if set_default {
        let config = Config {
            archive: Some(root.display().to_string()),
        };
        let path = config.save()?;
        println!("\nRecorded as the default archive in {}", path.display());
    } else {
        println!(
            "\nSentinel resolved this archive via the {}.\n\
             To make it the default from any directory:\n  \
             sentinel init {} --set-default",
            resolved.source.describe(),
            root.display()
        );
    }

    Ok(())
}

/// An archive may be created in a directory that is empty, or that is already
/// an archive (re-running `init` must stay idempotent).
fn is_safe_to_initialize(root: &std::path::Path) -> io::Result<bool> {
    if !root.exists() || paths::manifest_path().is_file() {
        return Ok(true);
    }
    let mut entries = fs::read_dir(root)?.filter_map(Result::ok).filter(|e| {
        // Ignore the bookkeeping a fresh checkout or editor leaves behind.
        !matches!(
            e.file_name().to_string_lossy().as_ref(),
            ".git" | ".DS_Store" | ".gitignore"
        )
    });
    Ok(entries.next().is_none())
}
