use std::fs;
use std::io;

use crate::core::paths::{self, Config, ResolvedRoot, RootSource};

pub fn run(resolved: &ResolvedRoot, set_default: bool) -> io::Result<()> {
    let root = paths::archive_root();

    // Falling back to the working directory is convenient in an empty folder and
    // reckless in a populated one — refuse to scatter an archive across someone's
    // home directory or source tree just because they forgot the path argument.
    if resolved.source == RootSource::Cwd && !is_safe_to_initialize(&root)? {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            format!(
                "Refusing to initialize an archive in the non-empty directory {}.\n\
                 Pass an explicit path: `sentinel init <PATH>`.",
                root.display()
            ),
        ));
    }

    // Create directory structure
    let dirs = [
        paths::raw_dir(),
        paths::wiki_dir(),
        paths::index_dir(),
        paths::meta_dir(),
        paths::templates_dir(),
    ];

    for dir in &dirs {
        fs::create_dir_all(dir)?;
    }

    // Create domain subdirectories in both raw/ and wiki/
    for domain in paths::DEFAULT_DOMAINS {
        fs::create_dir_all(paths::raw_domain_dir(domain))?;
        fs::create_dir_all(paths::wiki_domain_dir(domain))?;
    }

    // Create empty manifest if it doesn't exist
    let manifest_path = paths::manifest_path();
    if !manifest_path.exists() {
        fs::write(&manifest_path, r#"{"entries":{}}"#)?;
    }

    // Create empty link graph if it doesn't exist
    let link_graph_path = paths::link_graph_path();
    if !link_graph_path.exists() {
        fs::write(&link_graph_path, r#"{"forward":{},"backlinks":{}}"#)?;
    }

    // Create activity log if it doesn't exist
    let log_path = paths::log_path();
    if !log_path.exists() {
        fs::write(
            &log_path,
            "# Activity Log\n\n*Append-only record of sentinel operations. Parseable: `grep \"^## \\[\" meta/log.md`*\n\n",
        )?;
    }

    // Create wiki article template
    let wiki_template = paths::templates_dir().join("wiki-article.md");
    if !wiki_template.exists() {
        fs::write(
            &wiki_template,
            r#"---
title:
domain:
origin: authored
tags: []
sources: []
related: []
created:
updated:
status: draft
---

"#,
        )?;
    }

    // Create raw note template
    let raw_template = paths::templates_dir().join("raw-note.md");
    if !raw_template.exists() {
        fs::write(
            &raw_template,
            r#"---
title:
domain:
origin: authored
ingested:
---

"#,
        )?;
    }

    // Create empty index files
    let index_files = [
        (
            "_master.md",
            "# Master Index\n\n*Auto-generated by sentinel. Do not edit manually.*\n",
        ),
        (
            "_by-domain.md",
            "# Index by Domain\n\n*Auto-generated by sentinel. Do not edit manually.*\n",
        ),
        (
            "_recent.md",
            "# Recently Modified\n\n*Auto-generated by sentinel. Do not edit manually.*\n",
        ),
        (
            "_orphans.md",
            "# Orphan Pages\n\n*Pages with no incoming backlinks. Auto-generated by sentinel.*\n",
        ),
        (
            "_uncompiled.md",
            "# Uncompiled Sources\n\n*Raw documents no wiki article cites in its `sources:`. Auto-generated by sentinel.*\n",
        ),
    ];

    for (name, content) in &index_files {
        let path = paths::index_dir().join(name);
        if !path.exists() {
            fs::write(&path, content)?;
        }
    }

    // Create SUMMARY.md if it doesn't exist
    let summary_path = root.join("SUMMARY.md");
    if !summary_path.exists() {
        fs::write(
            &summary_path,
            "# Archive Knowledge Base\n\nA personal knowledge base compiled and maintained by Claude Code.\n\n## Domains\n\n- **Philosophy** — Personal philosophical writings and explorations\n- **Coding** — Software engineering knowledge, patterns, and codebase analyses\n- **Research** — Research topics and findings\n\n## Structure\n\n- `raw/` — Source documents (ingested, untouched)\n- `wiki/` — Compiled knowledge articles\n- `index/` — Auto-generated indexes\n- `meta/` — Machine-readable state (manifest, link graph)\n- `templates/` — Article templates\n",
        )?;
    }

    crate::core::log::append("init", "Archive initialized")?;

    println!("Archive initialized at {}", root.display());
    println!("  raw/       — source documents");
    println!("  wiki/      — compiled knowledge");
    println!("  index/     — auto-generated indexes");
    println!("  meta/      — manifest, link graph, activity log");
    println!("  templates/ — article templates");

    if set_default {
        let config = Config {
            archive: Some(root.display().to_string()),
        };
        let path = config.save()?;
        println!("\nRecorded as the default archive in {}", path.display());
    } else {
        println!(
            "\nSentinel resolved this archive via the {}.\n\
             To make it the default from any directory:\n  \
             sentinel init {} --set-default",
            resolved.source.describe(),
            root.display()
        );
    }

    Ok(())
}

/// An archive may be created in a directory that is empty, or that is already
/// an archive (re-running `init` must stay idempotent).
fn is_safe_to_initialize(root: &std::path::Path) -> io::Result<bool> {
    if !root.exists() || paths::manifest_path().is_file() {
        return Ok(true);
    }
    let mut entries = fs::read_dir(root)?.filter_map(Result::ok).filter(|e| {
        // Ignore the bookkeeping a fresh checkout or editor leaves behind.
        !matches!(
            e.file_name().to_string_lossy().as_ref(),
            ".git" | ".DS_Store" | ".gitignore"
        )
    });
    Ok(entries.next().is_none())
}
