use std::collections::BTreeSet;
use std::io;

use colored::Colorize;
use serde::Serialize;

use crate::core::frontmatter;
use crate::core::lint::{self, RuleInfo};
use crate::core::output;
use crate::core::paths;

/// The archive's contract, in one call.
///
/// An agent writing a wiki article needs to know the frontmatter fields, which
/// are required, what values the enums accept, which domains exist, and what
/// will be flagged. Every skill previously restated all of that in prose, and
/// the prose drifted — `/sentinel-compile` documented five domains where the
/// code had three. Publishing the contract from the code makes that class of
/// mismatch impossible.
#[derive(Serialize)]
struct Schema {
    frontmatter: &'static [Field],
    domains: Domains,
    layout: &'static [Directory],
    lint_rules: &'static [RuleInfo],
    next_actions: &'static [NextAction],
}

#[derive(Serialize)]
struct Field {
    name: &'static str,
    required: bool,
    #[serde(rename = "type")]
    kind: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    values: Option<&'static [&'static str]>,
    description: &'static str,
}

#[derive(Serialize)]
struct Domains {
    /// Created by `sentinel init`.
    default: &'static [&'static str],
    /// Actually present in this archive, from disk.
    present: Vec<String>,
}

#[derive(Serialize)]
struct Directory {
    name: &'static str,
    purpose: &'static str,
}

#[derive(Serialize)]
struct NextAction {
    priority: u8,
    action: &'static str,
    description: &'static str,
}

const FIELDS: &[Field] = &[
    Field {
        name: "title",
        required: true,
        kind: "string",
        values: None,
        description: "Human-readable title. Used as the display name in every generated index.",
    },
    Field {
        name: "domain",
        required: true,
        kind: "string",
        values: None,
        description: "Subject area. Should match the wiki/ subdirectory the article lives in.",
    },
    Field {
        name: "origin",
        required: true,
        kind: "enum",
        values: Some(frontmatter::ORIGINS),
        description: "Provenance. authored = distilled from the user's own writing; researched = gathered by an agent; hybrid = the user's ideas enriched with research.",
    },
    Field {
        name: "tags",
        required: false,
        kind: "string[]",
        values: None,
        description: "Topic tags.",
    },
    Field {
        name: "sources",
        required: false,
        kind: "string[]",
        values: None,
        description: "Archive-relative paths to the raw documents this was compiled from, e.g. raw/philosophy/meditations.md. This is what marks a raw document as compiled — an article with no sources leaves its source in the uncompiled queue forever.",
    },
    Field {
        name: "related",
        required: false,
        kind: "string[]",
        values: None,
        description: "Wikilinks to related articles, e.g. \"[[stoicism]]\".",
    },
    Field {
        name: "created",
        required: false,
        kind: "date",
        values: None,
        description: "YYYY-MM-DD.",
    },
    Field {
        name: "updated",
        required: false,
        kind: "date",
        values: None,
        description: "YYYY-MM-DD. Drives index/_recent.md and the stale-draft check in `sentinel next`.",
    },
    Field {
        name: "status",
        required: false,
        kind: "enum",
        values: Some(frontmatter::STATUSES),
        description: "Maturity of the article.",
    },
];

const LAYOUT: &[Directory] = &[
    Directory {
        name: "raw/",
        purpose: "Source documents. Immutable — never edited by sentinel or by an agent.",
    },
    Directory {
        name: "wiki/",
        purpose: "Compiled articles with YAML frontmatter. Agent-owned.",
    },
    Directory {
        name: "index/",
        purpose: "Generated by `sentinel index`. Never edit by hand; edits are overwritten.",
    },
    Directory {
        name: "meta/",
        purpose: "Machine state: manifest.json, link-graph.json, log.md.",
    },
    Directory {
        name: "templates/",
        purpose: "Article templates.",
    },
];

const NEXT_ACTIONS: &[NextAction] = &[
    NextAction {
        priority: 1,
        action: "fix-errors",
        description: "Lint errors exist. Every later judgement would be made on data they call into question.",
    },
    NextAction {
        priority: 2,
        action: "compile",
        description: "Raw documents no wiki article cites. Knowledge already in hand.",
    },
    NextAction {
        priority: 3,
        action: "write",
        description: "Wikilinks with no article behind them, ranked by how many distinct articles ask for each. The wiki naming its own gaps.",
    },
    NextAction {
        priority: 4,
        action: "connect",
        description: "Articles nothing links to.",
    },
    NextAction {
        priority: 5,
        action: "review",
        description: "Drafts untouched for over 30 days.",
    },
];

pub fn run() -> io::Result<()> {
    let schema = Schema {
        frontmatter: FIELDS,
        domains: Domains {
            default: paths::DEFAULT_DOMAINS,
            present: present_domains(),
        },
        layout: LAYOUT,
        lint_rules: lint::RULES,
        next_actions: NEXT_ACTIONS,
    };

    if output::is_json() {
        return output::emit("schema", schema);
    }

    println!("{}", "Wiki Article Frontmatter".bold());
    for field in schema.frontmatter {
        let required = if field.required {
            "required".red().to_string()
        } else {
            "optional".dimmed().to_string()
        };
        let kind = match field.values {
            Some(values) => values.join(" | "),
            None => field.kind.to_string(),
        };
        println!("  {:<10} {required}  {}", field.name.cyan(), kind.dimmed());
        println!("    {}", field.description);
    }

    println!("\n{}", "Domains".bold());
    println!("  created by init:  {}", schema.domains.default.join(", "));
    println!(
        "  present here:     {}",
        if schema.domains.present.is_empty() {
            "(none)".dimmed().to_string()
        } else {
            schema.domains.present.join(", ")
        }
    );

    println!("\n{}", "Layout".bold());
    for dir in schema.layout {
        println!("  {:<12} {}", dir.name.cyan(), dir.purpose);
    }

    println!("\n{}", "Lint Rules".bold());
    for rule in schema.lint_rules {
        let tag = match rule.severity {
            lint::Severity::Error => rule.severity.label().red(),
            lint::Severity::Warning => rule.severity.label().yellow(),
        };
        println!("  {tag:<7} {}", rule.rule.cyan());
        println!("    {}", rule.description);
    }

    println!("\n{}", "`sentinel next` Priority".bold());
    for action in schema.next_actions {
        println!("  {}. {}", action.priority, action.action.cyan());
        println!("     {}", action.description);
    }

    Ok(())
}

/// Domains that actually exist, as the union of `raw/` and `wiki/` subdirectories.
///
/// Reported from disk rather than from a constant so the answer describes this
/// archive rather than a default the user may have moved past.
fn present_domains() -> Vec<String> {
    let mut domains = BTreeSet::new();
    for dir in [paths::raw_dir(), paths::wiki_dir()] {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.filter_map(Result::ok) {
            if !entry.file_type().is_ok_and(|t| t.is_dir()) {
                continue;
            }
            let name = entry.file_name().to_string_lossy().to_string();
            if !name.starts_with('.') {
                domains.insert(name);
            }
        }
    }
    domains.into_iter().collect()
}
